/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Random;

public class App {
    public void coinFlip(int n, double p) {
        
        Random random = new Random();
        int chanceOfHeads = (int) (p * 100);
        for (int i = 1; i < 11; i++) {
            int headsCount = 0;
            for (int j = 0; j < n; j++) {
                int randomNumber = random.nextInt(99);
            
                if (randomNumber < chanceOfHeads) {
                    headsCount++;
                }
            }
    
            System.out.println("Number of Flips (n): " + n + "| Trial number (m): " + i + "| Probability of Heads (p): " + p + "| Number of Heads: " + headsCount);
        }
    }


    public static void main(String[] args) {
        App app = new App();

        app.coinFlip(10, 0.5);
        app.coinFlip(10, 0.7);
        app.coinFlip(10, 0.9);

        app.coinFlip(100, 0.5);
        app.coinFlip(100, 0.7);
        app.coinFlip(100, 0.9);

        app.coinFlip(1000, 0.5);
        app.coinFlip(1000, 0.7);
        app.coinFlip(1000, 0.9);

        app.coinFlip(10000, 0.5);
        app.coinFlip(10000, 0.7);
        app.coinFlip(10000, 0.9);

        app.coinFlip(100000, 0.5);
        app.coinFlip(100000, 0.7);
        app.coinFlip(100000, 0.9);
    }
}